### ISSUE TITLE
Basic Landing Page

### ISSUE THREAD

**Issue by AndreasInk** [Vito-Research/Vito-Website#1]
- Header and subheader to the left and image to the right on Desktop, more vertical on mobile

**Comment by ithiel883** [comment]
can i work on this issue?

**Comment by AndreasInk** [comment]
Sure thing! Let me know if you need any help or have any questions :)

**Comment by AndreasInk** [comment]
Just a heads up @ithiel883 we are moving with a new design, here it is...
![Frame 1](https://user-images.githubusercontent.com/67549402/170849697-a69a821b-2ccd-4e60-a7ab-6a34eae15cb7.png)

**Comment by AndreasInk** [comment]
Would love your thoughts! @ithiel883 @patrickledew

**Comment by AndreasInk** [comment]
Complete!
