### ISSUE TITLE
Social Media Image SEO

### ISSUE THREAD

**Issue by AndreasInk** [Vito-Research/Vito-Website#17]
- For social media (Linkedin/Twitter/Discord), have a preview image

**Comment by Franqsanz** [comment]
Hi, how are you?
I would like to help you with this, the meta tags go inside the `index.html`, with the image "VitoPromo.png"?

**Comment by AndreasInk** [comment]
Hey, doing good, yup! I believe I tried to implement it but it did not appear on Twitter.

**Comment by AndreasInk** [comment]
> Hi, how are you?
> I would like to help you with this, the meta tags go inside the `index.html`, with the image "VitoPromo.png"?

Thanks for wanting to help out!

**Comment by Franqsanz** [comment]
You must add the domain of the site in "content"

example:
`<meta property="og:image" content="https://example.com/src/res/VitoPromo.png" />`

**Comment by AndreasInk** [comment]
Gotcha, that makes sense now!

**Comment by Franqsanz** [comment]
Yeaa, successes with your project!!!

**Comment by AndreasInk** [comment]
Thanks, if you ever want to help out anywhere else, lmk!
